CREATE TABLE IF NOT EXISTS yahoo_stock_tickers(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    ticker VARCHAR(16) NOT NULL,
    name VARCHAR(100) NOT NULL,
    exchange VARCHAR(3) NOT NULL,
    category VARCHAR(50) DEFAULT NULL,
    country VARCHAR(50) NOT NULL,
    category_number INTEGER NOT NULL
);